service:
  name: glip-integration-js-1
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 256
  environment: ${file(./env.yml)}
  profile: default
  excludeDevDependencies: true
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - lambda:InvokeFunction
  #     Resource: "*"
package:
  include:
    - '*.json'
    - '*.js'
    - 'node_modules/**'
functions:
  app:
    handler: lambda.app
    timeout: 400 # 5 miutes
    # role: arn:aws:iam::111111:role/xxxx-prod-us-east-1-lambdaRole
    tags:
      department: dev
      Owner: Your name
      Stage: production
      Environment: your-env-tag
      Team: your-team
      Name: engage-digital-chatbot-1
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
